import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import Cta from '../components/sections/cta'
import Features from '../components/sections/features'
import Footer from '../components/sections/footer'
import Hero from '../components/sections/Hero'
import Stats from '../components/sections/stats'
import Works from '../components/sections/works'
import Spacing from '../components/Spacing'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Navbar />

        <Hero />

        <Spacing />

        <Features />

        <Spacing />

        <Works />

        <Spacing />


        <Stats />

        <Spacing />

        <Cta />

        <Footer />
      </main>
    </div>
  )
}
